"""Create the .lexibrary/ directory skeleton for a new project."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

from lexibrarian.config.defaults import DEFAULT_PROJECT_CONFIG_TEMPLATE
from lexibrarian.config.schema import LexibraryConfig
from lexibrarian.iwh.gitignore import ensure_iwh_gitignored

if TYPE_CHECKING:
    from lexibrarian.init.wizard import WizardAnswers

LEXIBRARY_DIR = ".lexibrary"

LEXIGNORE_HEADER = """\
# .lexignore — Lexibrarian-specific ignore patterns
# Files matching these patterns will NOT receive design files, even if tracked by git.
# Uses .gitignore format and rules.
# Example: **/migrations/
"""

START_HERE_PLACEHOLDER = """\
# START HERE

This library has not been generated yet.

Run `lexictl update` to crawl the project and generate the full Lexibrarian library.

## Inter-agent signals

Check for `.iwh` files in directories you are working in. These contain context
left by previous agent sessions — read them before starting work, and leave your
own `.iwh` file when handing off to another agent.
"""

_CONFIG_YAML_HEADER = """\
# Lexibrarian project configuration
# Generated by `lexictl init`
# Modify values below or re-run `lexictl init` to regenerate.

"""


def _generate_lexignore(patterns: list[str]) -> str:
    """Build ``.lexignore`` content from wizard-collected patterns.

    The output always starts with :data:`LEXIGNORE_HEADER`.  If *patterns*
    is non-empty, each pattern is appended on its own line.

    Args:
        patterns: Gitignore-style glob patterns to include.

    Returns:
        Complete ``.lexignore`` file content.
    """
    if not patterns:
        return LEXIGNORE_HEADER

    return LEXIGNORE_HEADER + "\n".join(patterns) + "\n"


def _generate_config_yaml(answers: WizardAnswers) -> str:
    """Build config YAML from wizard answers with Pydantic validation.

    Constructs a config dict from *answers*, validates it through
    :class:`~lexibrarian.config.schema.LexibraryConfig`, then serialises to
    YAML.  A ``ValidationError`` is raised before any output if the data
    is invalid.

    Args:
        answers: Completed wizard answers dataclass.

    Returns:
        YAML string including a header comment, ready to write to disk.
    """
    config_dict: dict[str, Any] = {
        "scope_root": answers.scope_root,
        "project_name": answers.project_name,
        "agent_environment": answers.agent_environments,
        "iwh": {"enabled": answers.iwh_enabled},
        "llm": {
            "provider": answers.llm_provider,
            "model": answers.llm_model,
            "api_key_env": answers.llm_api_key_env,
        },
    }

    if answers.token_budgets_customized and answers.token_budgets:
        config_dict["token_budgets"] = answers.token_budgets

    # Validate through Pydantic — raises ValidationError on bad data
    LexibraryConfig.model_validate(config_dict)

    return _CONFIG_YAML_HEADER + yaml.dump(
        config_dict,
        sort_keys=False,
        default_flow_style=False,
    )


def create_lexibrary_skeleton(project_root: Path) -> list[Path]:
    """Create the ``.lexibrary/`` directory skeleton at *project_root*.

    Idempotent — existing files are never overwritten.

    Args:
        project_root: Absolute path to the project root directory.

    Returns:
        List of paths that were created (empty if skeleton already exists).
    """
    base = project_root / LEXIBRARY_DIR
    created: list[Path] = []

    # Directories
    for subdir in [base, base / "concepts", base / "stack"]:
        if not subdir.exists():
            subdir.mkdir(parents=True)
            created.append(subdir)

    # .gitkeep files for empty directories
    for gitkeep in [base / "concepts" / ".gitkeep", base / "stack" / ".gitkeep"]:
        if not gitkeep.exists():
            gitkeep.touch()
            created.append(gitkeep)

    # Template files — never overwrite existing
    files: dict[Path, str] = {
        base / "config.yaml": DEFAULT_PROJECT_CONFIG_TEMPLATE,
        base / "START_HERE.md": START_HERE_PLACEHOLDER,
        project_root / ".lexignore": LEXIGNORE_HEADER,
    }
    for path, content in files.items():
        if not path.exists():
            path.write_text(content)
            created.append(path)

    # Ensure .iwh files are gitignored
    ensure_iwh_gitignored(project_root)

    return created


def create_lexibrary_from_wizard(
    project_root: Path,
    answers: WizardAnswers,
) -> list[Path]:
    """Create the ``.lexibrary/`` skeleton using wizard answers.

    Unlike :func:`create_lexibrary_skeleton`, this function generates the
    config file dynamically from *answers* rather than using a static
    template.

    Args:
        project_root: Absolute path to the project root directory.
        answers: Completed :class:`WizardAnswers` from the init wizard.

    Returns:
        List of all created file and directory paths.
    """
    base = project_root / LEXIBRARY_DIR
    created: list[Path] = []

    # Directories
    for subdir in [base, base / "concepts", base / "stack"]:
        if not subdir.exists():
            subdir.mkdir(parents=True)
            created.append(subdir)

    # .gitkeep files for empty directories
    for gitkeep in [base / "concepts" / ".gitkeep", base / "stack" / ".gitkeep"]:
        if not gitkeep.exists():
            gitkeep.touch()
            created.append(gitkeep)

    # Config from wizard answers (validated through Pydantic)
    config_path = base / "config.yaml"
    if not config_path.exists():
        config_path.write_text(_generate_config_yaml(answers))
        created.append(config_path)

    # START_HERE.md placeholder
    start_here_path = base / "START_HERE.md"
    if not start_here_path.exists():
        start_here_path.write_text(START_HERE_PLACEHOLDER)
        created.append(start_here_path)

    # .lexignore with wizard-provided patterns
    lexignore_path = project_root / ".lexignore"
    if not lexignore_path.exists():
        lexignore_path.write_text(_generate_lexignore(answers.ignore_patterns))
        created.append(lexignore_path)

    # Ensure .iwh files are gitignored
    ensure_iwh_gitignored(project_root)

    return created
